### ISSUE TITLE
Solution logic

### ISSUE THREAD

**Issue by krishnaanaril** [morris821028/UVa#18]
Hi morris821028,

It'll be great if you could briefly describe the logic of your solution.

Thanks,

**Comment by krishnaanaril** [comment]
For the UVA Problem 11277 - Cyclic Polygon

**Comment by morris821028** [comment]
Because all of its vertices lie on a circle, we can find radius of circle by binary search. Then, what is key in binary search ?

The edge of polygon is considered as chord (geometry) of circle, and each chord is bound by an arc. We get summation of arc equals 2 pi. In order to get all of arcs, binary search radius of circle.

I hope poor English description can help you.

**Comment by krishnaanaril** [comment]
Great. Thanks a lot for the quick response.

**Comment by mnoor4** [comment]
hey morris821028, it'll be great if you could explain the formulas used for problem p1011 crossing the desert. thankyou :)
